# Generated by Django 5.0 on 2024-06-20 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='products',
            old_name='product_price',
            new_name='price',
        ),
    ]
