# Generated by Django 5.0 on 2024-06-21 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0002_rename_product_description_products_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_image',
            new_name='image',
        ),
    ]
