# Generated by Django 5.0 on 2024-06-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0004_remove_products_image_products_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='lecture',
            field=models.FileField(blank=True, null=True, upload_to='image/'),
        ),
    ]
