# Generated by Django 5.0 on 2024-06-21 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0005_alter_products_lecture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='lecture',
            new_name='image',
        ),
    ]
