# Generated by Django 5.0 on 2024-07-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0011_city_customuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
