# Generated by Django 5.0 on 2024-07-03 17:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0012_delete_customuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(default='', max_length=20)),
                ('phone', models.CharField(default='', max_length=15)),
                ('address', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to='stati/image')),
                ('cart', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zayapp.cart')),
                ('city', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='zayapp.city')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
