# Generated by Django 5.0 on 2024-07-03 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0014_nations_userprofile_nationality'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.FileField(blank=True, upload_to='static/image'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nationality',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.SET_DEFAULT, to='zayapp.nations'),
        ),
    ]
