# Generated by Django 5.0 on 2024-07-04 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0015_alter_userprofile_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='', max_length=155)),
                ('message', models.TextField()),
                ('user', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='zayapp.userprofile')),
            ],
        ),
    ]
