# Generated by Django 5.0 on 2024-07-05 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0018_contact_email_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='Custom_id',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
