# Generated by Django 5.0 on 2024-07-14 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0020_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zayapp.cartitem'),
        ),
    ]
