# Generated by Django 5.0 on 2024-07-14 21:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zayapp', '0022_order_data_alter_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zayapp.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='cart',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='zayapp.cart'),
        ),
    ]
